---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/7/4 23:32
---

---练习12.6 ：请编写一个函数，该函数用于计算两个指定日期之间相差的月份。
local function CountGapMonth(date1, date2)
    local d = os.difftime(date2, date1)
    return os.date("%m", d)
end

-- test
local t5_2 = os.time({year = 2015, month=1, day=12})
local t5_3 = os.time({year = 2015, month=11, day=11})
print(CountGapMonth(t5_2, t5_3))

--- 练习12.8 ：请编写一个函数，该函数用于输出操作系统的时区。
-- 出现输出乱码
local function GetTimeZone()
    local t = os.date("*t") --获取当前时间
    return os.date("%z", os.time(t))
end


-- test
print(GetTimeZone())