---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/2/25 11:17
---
local Person = {}
function Person:sayHello()
    print('Hi!')
end

function ifelsefunctiontest(op)
    if op =="the" then
        print(op)
    elseif op =="-" then
        print(op)
    end

end

Person:sayHello()

ifelsefunctiontest("the")